[alembic]
script_location = alembic
sqlalchemy.url = postgresql+psycopg://kognito_user:hJxsw8569LJ@localhost:5432/kognito_db
# autogenerate with --autogenerate
# revision with --autogenerate -m "message"
# upgrade head
# downgrade base