"""Add new fields to Account model

Revision ID: 0eca9c52eb37
Revises: e4464a48c948
Create Date: 2025-11-25 17:50:38.571086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0eca9c52eb37'
down_revision: Union[str, Sequence[str], None] = 'e4464a48c948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_chat_history')
    op.add_column('accounts', sa.Column('phone', sa.String(length=255), nullable=True, comment='Número de teléfono del usuario.'))
    op.add_column('accounts', sa.Column('bio', sa.Text(), nullable=True, comment='Biografía o descripción personal del usuario.'))
    op.add_column('accounts', sa.Column('profiles_enabled', sa.Boolean(), nullable=True, comment='Indica si el módulo de perfiles está habilitado para la cuenta.'))
    op.execute(sa.text("UPDATE accounts SET profiles_enabled = TRUE WHERE profiles_enabled IS NULL"))
    op.alter_column('accounts', 'profiles_enabled', existing_type=sa.Boolean(), nullable=False, server_default=sa.text('TRUE'))

    op.add_column('accounts', sa.Column('galleries_enabled', sa.Boolean(), nullable=True, comment='Indica si el módulo de galerías está habilitado para la cuenta.'))
    op.execute(sa.text("UPDATE accounts SET galleries_enabled = TRUE WHERE galleries_enabled IS NULL"))
    op.alter_column('accounts', 'galleries_enabled', existing_type=sa.Boolean(), nullable=False, server_default=sa.text('TRUE'))

    op.add_column('accounts', sa.Column('forms_enabled', sa.Boolean(), nullable=True, comment='Indica si el módulo de formularios está habilitado para la cuenta.'))
    op.execute(sa.text("UPDATE accounts SET forms_enabled = TRUE WHERE forms_enabled IS NULL"))
    op.alter_column('accounts', 'forms_enabled', existing_type=sa.Boolean(), nullable=False, server_default=sa.text('TRUE'))

    op.add_column('accounts', sa.Column('theme', sa.String(length=50), nullable=True, comment="Tema de la interfaz de usuario (e.g., 'light', 'dark', 'system')."))
    op.execute(sa.text("UPDATE accounts SET theme = 'system' WHERE theme IS NULL"))
    op.alter_column('accounts', 'theme', existing_type=sa.String(length=50), nullable=False, server_default=sa.text("'system'"))

    op.add_column('accounts', sa.Column('notifications_email', sa.Boolean(), nullable=True, comment='Indica si las notificaciones por correo electrónico están habilitadas.'))
    op.execute(sa.text("UPDATE accounts SET notifications_email = TRUE WHERE notifications_email IS NULL"))
    op.alter_column('accounts', 'notifications_email', existing_type=sa.Boolean(), nullable=False, server_default=sa.text('TRUE'))

    op.add_column('accounts', sa.Column('notifications_push', sa.Boolean(), nullable=True, comment='Indica si las notificaciones push están habilitadas.'))
    op.execute(sa.text("UPDATE accounts SET notifications_push = TRUE WHERE notifications_push IS NULL"))
    op.alter_column('accounts', 'notifications_push', existing_type=sa.Boolean(), nullable=False, server_default=sa.text('TRUE'))

    op.add_column('accounts', sa.Column('language', sa.String(length=10), nullable=True, comment="Idioma preferido de la interfaz de usuario (e.g., 'en', 'es')."))
    op.execute(sa.text("UPDATE accounts SET language = 'en' WHERE language IS NULL"))
    op.alter_column('accounts', 'language', existing_type=sa.String(length=10), nullable=False, server_default=sa.text("'en'"))

    op.add_column('accounts', sa.Column('privacy_data_sharing', sa.Boolean(), nullable=True, comment='Indica si el usuario permite compartir datos para mejoras del servicio.'))
    op.execute(sa.text("UPDATE accounts SET privacy_data_sharing = FALSE WHERE privacy_data_sharing IS NULL"))
    op.alter_column('accounts', 'privacy_data_sharing', existing_type=sa.Boolean(), nullable=False, server_default=sa.text('FALSE'))
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.drop_column('accounts', 'privacy_data_sharing')
    op.drop_column('accounts', 'language')
    op.drop_column('accounts', 'notifications_push')
    op.drop_column('accounts', 'notifications_email')
    op.drop_column('accounts', 'theme')
    op.drop_column('accounts', 'forms_enabled')
    op.drop_column('accounts', 'galleries_enabled')
    op.drop_column('accounts', 'profiles_enabled')
    op.drop_column('accounts', 'bio')
    op.drop_column('accounts', 'phone')
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    # ### end Alembic commands ###
