"""add_hidden_from_sidebar_to_chat_threads

Revision ID: 0fd9fd0e16e2
Revises: 464a9aac6c0a
Create Date: 2026-05-21 22:05:47.597096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fd9fd0e16e2'
down_revision: Union[str, Sequence[str], None] = '464a9aac6c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_threads', sa.Column('hidden_from_sidebar', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_threads', 'hidden_from_sidebar')
    # ### end Alembic commands ###

