"""Add OnlyOffice folders and workspace support

Revision ID: 22fe389484a9
Revises: e5f6a7b8c9d0
Create Date: 2026-04-01 03:47:56.839898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22fe389484a9'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onlyoffice_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['onlyoffice_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onlyoffice_folders_account_id'), 'onlyoffice_folders', ['account_id'], unique=False)
    op.create_index(op.f('ix_onlyoffice_folders_parent_id'), 'onlyoffice_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_onlyoffice_folders_workspace_id'), 'onlyoffice_folders', ['workspace_id'], unique=False)
    
    op.add_column('onlyoffice_documents', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_onlyoffice_documents_folder_id'), 'onlyoffice_documents', ['folder_id'], unique=False)
    op.create_foreign_key('fk_onlyoffice_documents_folder_id', 'onlyoffice_documents', 'onlyoffice_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_onlyoffice_documents_folder_id', 'onlyoffice_documents', type_='foreignkey')
    op.drop_index(op.f('ix_onlyoffice_documents_folder_id'), table_name='onlyoffice_documents')
    op.drop_column('onlyoffice_documents', 'folder_id')
    
    op.drop_index(op.f('ix_onlyoffice_folders_workspace_id'), table_name='onlyoffice_folders')
    op.drop_index(op.f('ix_onlyoffice_folders_parent_id'), table_name='onlyoffice_folders')
    op.drop_index(op.f('ix_onlyoffice_folders_account_id'), table_name='onlyoffice_folders')
    op.drop_table('onlyoffice_folders')
    # ### end Alembic commands ###
