"""add_visual_content_to_notes

Revision ID: 298617640581
Revises: bb9b21bbc3c9
Create Date: 2026-01-10 02:30:45.967816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '298617640581'
down_revision: Union[str, Sequence[str], None] = 'bb9b21bbc3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_chat_history')
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    op.add_column('notas', sa.Column('visual_content', sa.Text(), nullable=True, comment='Contenido HTML generado por OnlyOffice para preservar el diseño visual.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'visual_content')
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    # ### end Alembic commands ###
