"""Añadir campo status a la tabla Task

Revision ID: 40a71dbe5a5d
Revises: fdc15411c20d
Create Date: 2025-11-18 21:51:27.680761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a71dbe5a5d'
down_revision: Union[str, Sequence[str], None] = 'fdc15411c20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS langchain_chat_history')
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    op.add_column('tasks', sa.Column('status', sa.String(length=50), nullable=True, comment='Estado de la tarea para tableros Kanban (ej. Pendiente, En Progreso, Completado).'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    # ### end Alembic commands ###
