"""Add embedding configuration to Account model

Revision ID: 4511159c8ca0
Revises: eeedefc8932c
Create Date: 2026-02-11 22:39:19.377324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4511159c8ca0'
down_revision: Union[str, Sequence[str], None] = 'eeedefc8932c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('embedding_provider', sa.String(length=50), nullable=True, comment="Proveedor de Embeddings preferido (e.g., 'ollama', 'openai', 'google')."))
    op.add_column('accounts', sa.Column('embedding_model', sa.String(length=255), nullable=True, comment='Modelo de Embeddings preferido.'))
    op.add_column('accounts', sa.Column('embedding_api_key_name', sa.String(length=255), nullable=True, comment='Nombre de la clave API en UserSecret para el proveedor de Embeddings.'))
    op.add_column('accounts', sa.Column('embedding_api_base', sa.String(length=255), nullable=True, comment='URL base opcional para la API de Embeddings (ej. Ollama, Local).'))
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.drop_column('accounts', 'embedding_api_base')
    op.drop_column('accounts', 'embedding_api_key_name')
    op.drop_column('accounts', 'embedding_model')
    op.drop_column('accounts', 'embedding_provider')
    # ### end Alembic commands ###
