"""add_is_starred_to_nota

Revision ID: 464a9aac6c0a
Revises: 20260510_add_workspace_id_to_proactive_insights
Create Date: 2026-05-17 17:35:52.130162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '464a9aac6c0a'
down_revision: Union[str, Sequence[str], None] = '20260510_add_workspace_id_to_proactive_insights'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('is_starred', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'is_starred')
    # ### end Alembic commands ###
