"""add_llm_config_fields_to_account

Revision ID: 6b2cd28cd638
Revises: 298617640581
Create Date: 2026-02-03 05:24:31.708684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b2cd28cd638'
down_revision: Union[str, Sequence[str], None] = '298617640581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_changes')
    op.drop_table('task_result')
    op.drop_table('langchain_chat_history')
    op.add_column('accounts', sa.Column('llm_provider', sa.String(length=50), nullable=True, comment='Proveedor de LLM preferido (openai, google, anthropic, etc.).'))
    op.add_column('accounts', sa.Column('llm_model', sa.String(length=255), nullable=True, comment='Modelo de LLM principal preferido.'))
    op.add_column('accounts', sa.Column('llm_temperature', sa.Float(), nullable=True, comment='Temperatura para la generación de texto.'))
    op.add_column('accounts', sa.Column('llm_api_base', sa.String(length=255), nullable=True, comment='URL base opcional para la API del LLM (ej. Ollama, Local).'))
    op.add_column('accounts', sa.Column('fast_llm_model', sa.String(length=255), nullable=True, comment='Modelo de LLM para tareas rápidas.'))
    op.add_column('accounts', sa.Column('vision_llm_model', sa.String(length=255), nullable=True, comment='Modelo de LLM para tareas de visión.'))
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.drop_column('accounts', 'vision_llm_model')
    op.drop_column('accounts', 'fast_llm_model')
    op.drop_column('accounts', 'llm_api_base')
    op.drop_column('accounts', 'llm_temperature')
    op.drop_column('accounts', 'llm_model')
    op.drop_column('accounts', 'llm_provider')
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    op.create_table('task_result',
    sa.Column('tenant', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('status_info', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_open_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_index', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('change_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('callback', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('baseurl', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tenant', 'id', name=op.f('task_result_pkey'))
    )
    op.create_table('doc_changes',
    sa.Column('tenant', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('change_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id_original', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('change_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('change_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tenant', 'id', 'change_id', name=op.f('doc_changes_pkey'))
    )
    # ### end Alembic commands ###
