"""Add text_search_vector to Nota model

Revision ID: 6f9993f6ad72
Revises: 3552a6d5af7d
Create Date: 2025-11-06 06:11:20.076304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f9993f6ad72'
down_revision: Union[str, Sequence[str], None] = '3552a6d5af7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process_status')
    op.drop_table('langchain_chat_history')
    op.drop_table('chat_message_history')
    op.drop_table('note_profile_links')
    op.alter_column('agenda_events', 'summary',
               existing_type=sa.VARCHAR(),
               comment='Resumen conciso del evento.',
               existing_nullable=False)
    op.alter_column('agenda_events', 'description',
               existing_type=sa.TEXT(),
               comment='Descripción detallada del evento.',
               existing_nullable=True)
    op.alter_column('agenda_events', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment='Ubicación del evento.',
               existing_nullable=True)
    op.alter_column('agenda_events', 'external_attendees',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Nombres de asistentes no registrados.',
               existing_nullable=True)
    op.drop_index(op.f('ix_agenda_events_team_id'), table_name='agenda_events')
    op.create_index(op.f('ix_agenda_events_workspace_id'), 'agenda_events', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('agenda_events_team_id_fkey'), 'agenda_events', type_='foreignkey')
    op.create_foreign_key(None, 'agenda_events', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('agenda_events', 'is_task')
    op.drop_column('agenda_events', 'team_id')
    op.drop_column('agenda_events', 'is_completed')
    op.alter_column('contact_profiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               comment='Nombre del contacto.')
    op.alter_column('contact_profiles', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Email del contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'phone',
               existing_type=sa.VARCHAR(length=255),
               comment='Número de teléfono del contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Etiquetas asociadas al contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'category',
               existing_type=sa.VARCHAR(length=255),
               comment='Categoría del contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Campos personalizados para el contacto.',
               existing_nullable=True)
    op.create_foreign_key(None, 'form_contact_profiles_association', 'forms', ['form_id'], ['id'])
    op.alter_column('forms', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el formulario es accesible públicamente.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_langchain_pg_embedding_team_id'), table_name='langchain_pg_embedding')
    op.drop_index(op.f('idx_langchain_pg_embedding_text_search_vector'), table_name='langchain_pg_embedding', postgresql_using='gin')
    op.drop_index(op.f('ix_langchain_pg_embedding_team_id'), table_name='langchain_pg_embedding')
    op.create_index(op.f('ix_langchain_pg_embedding_telegram_id'), 'langchain_pg_embedding', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_langchain_pg_embedding_thread_id'), 'langchain_pg_embedding', ['thread_id'], unique=False)
    op.drop_column('langchain_pg_embedding', 'team_id')
    op.drop_column('langchain_pg_embedding', 'visibility_teams')
    op.add_column('notas', sa.Column('text_search_vector', postgresql.TSVECTOR(), nullable=True))
    op.drop_index(op.f('ix_notas_team_id'), table_name='notas')
    op.create_index('ix_notas_text_search_vector', 'notas', ['text_search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_notas_workspace_id'), 'notas', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('notas_team_id_fkey'), 'notas', type_='foreignkey')
    op.drop_column('notas', 'is_featured')
    op.drop_column('notas', 'team_id')
    op.execute('UPDATE photos SET "order" = 0 WHERE "order" IS NULL')
    op.alter_column('photos', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_proactive_insights_team_id'), table_name='proactive_insights')
    op.drop_constraint(op.f('proactive_insights_team_id_fkey'), 'proactive_insights', type_='foreignkey')
    op.drop_column('proactive_insights', 'team_id')
    op.add_column('recordatorios', sa.Column('message', sa.Text(), nullable=True))
    op.execute('UPDATE recordatorios SET message = text')
    op.alter_column('recordatorios', 'message',
               existing_type=sa.Text(),
               nullable=False)
    op.drop_column('recordatorios', 'text')
    op.create_foreign_key(None, 'task_contact_profiles_association', 'contact_profiles', ['contact_profile_id'], ['id'])
    op.drop_index(op.f('ix_tasks_team_id'), table_name='tasks')
    op.drop_constraint(op.f('tasks_team_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'team_id')
    op.add_column('team_members', sa.Column('role', sa.String(length=50), nullable=False, comment='Rol del miembro en el equipo (ej. admin, member).'))
    op.add_column('team_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('team_members', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.alter_column('team_members', 'id', server_default=None)
    op.alter_column('team_members', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='uuid_generate_v4()')
    op.alter_column('team_members', 'id', server_default=sa.text('uuid_generate_v4()'))
    op.drop_constraint(op.f('_team_account_uc'), 'team_members', type_='unique')
    op.create_unique_constraint('_team_account_member_uc', 'team_members', ['team_id', 'account_id'])
    op.create_index('ix_team_member_account_id', 'team_members', ['account_id'], unique=False)
    op.create_index('ix_team_member_team_id', 'team_members', ['team_id'], unique=False)
    op.drop_constraint(op.f('team_members_team_id_fkey'), 'team_members', type_='foreignkey')
    op.drop_constraint(op.f('team_members_account_id_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'team_members', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_column('team_members', 'joined_at')
    op.drop_index(op.f('ix_account_team_topic'), table_name='user_document_topics', postgresql_where='(team_id IS NOT NULL)')
    op.drop_index(op.f('ix_user_document_topics_team_id'), table_name='user_document_topics')
    op.drop_constraint(op.f('user_document_topics_team_id_fkey'), 'user_document_topics', type_='foreignkey')
    op.drop_column('user_document_topics', 'team_id')
    op.alter_column('workspaces', 'color',
               existing_type=sa.VARCHAR(length=7),
               comment='Color asociado al workspace (ej. #RRGGBB).',
               existing_nullable=True,
               existing_server_default=sa.text("'#007bff'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'color',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='Color asociado al workspace (ej. #RRGGBB).',
               existing_nullable=True,
               existing_server_default=sa.text("'#007bff'::character varying"))
    op.add_column('user_document_topics', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_document_topics_team_id_fkey'), 'user_document_topics', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_document_topics_team_id'), 'user_document_topics', ['team_id'], unique=False)
    op.create_index(op.f('ix_account_team_topic'), 'user_document_topics', ['account_id', 'team_id', 'name'], unique=True, postgresql_where='(team_id IS NOT NULL)')
    op.add_column('team_members', sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_account_id_fkey'), 'team_members', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(op.f('team_members_team_id_fkey'), 'team_members', 'teams', ['team_id'], ['id'])
    op.drop_index('ix_team_member_team_id', table_name='team_members')
    op.drop_index('ix_team_member_account_id', table_name='team_members')
    op.drop_constraint('_team_account_member_uc', 'team_members', type_='unique')
    op.create_unique_constraint(op.f('_team_account_uc'), 'team_members', ['team_id', 'account_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('team_members', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('team_members', 'updated_at')
    op.drop_column('team_members', 'created_at')
    op.drop_column('team_members', 'role')
    op.add_column('tasks', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tasks_team_id_fkey'), 'tasks', 'teams', ['team_id'], ['id'])
    op.create_index(op.f('ix_tasks_team_id'), 'tasks', ['team_id'], unique=False)
    op.drop_constraint(None, 'task_contact_profiles_association', type_='foreignkey')
    op.add_column('recordatorios', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('recordatorios', 'message')
    op.add_column('proactive_insights', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('proactive_insights_team_id_fkey'), 'proactive_insights', 'teams', ['team_id'], ['id'])
    op.create_index(op.f('ix_proactive_insights_team_id'), 'proactive_insights', ['team_id'], unique=False)
    op.alter_column('photos', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('notas', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notas', sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('notas_team_id_fkey'), 'notas', 'teams', ['team_id'], ['id'])
    op.drop_index(op.f('ix_notas_workspace_id'), table_name='notas')
    op.drop_index('ix_notas_text_search_vector', table_name='notas', postgresql_using='gin')
    op.create_index(op.f('ix_notas_team_id'), 'notas', ['team_id'], unique=False)
    op.drop_column('notas', 'text_search_vector')
    op.add_column('langchain_pg_embedding', sa.Column('visibility_teams', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('langchain_pg_embedding', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_langchain_pg_embedding_thread_id'), table_name='langchain_pg_embedding')
    op.drop_index(op.f('ix_langchain_pg_embedding_telegram_id'), table_name='langchain_pg_embedding')
    op.create_index(op.f('ix_langchain_pg_embedding_team_id'), 'langchain_pg_embedding', ['team_id'], unique=False)
    op.create_index(op.f('idx_langchain_pg_embedding_text_search_vector'), 'langchain_pg_embedding', ['text_search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_langchain_pg_embedding_team_id'), 'langchain_pg_embedding', ['team_id'], unique=False)
    op.alter_column('forms', 'is_public',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica si el formulario es accesible públicamente.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'form_contact_profiles_association', type_='foreignkey')
    op.alter_column('contact_profiles', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Campos personalizados para el contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'category',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Categoría del contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Etiquetas asociadas al contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'phone',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Número de teléfono del contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Email del contacto.',
               existing_nullable=True)
    op.alter_column('contact_profiles', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               comment=None,
               existing_comment='Nombre del contacto.')
    op.add_column('agenda_events', sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('agenda_events', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('agenda_events', sa.Column('is_task', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agenda_events', type_='foreignkey')
    op.create_foreign_key(op.f('agenda_events_team_id_fkey'), 'agenda_events', 'teams', ['team_id'], ['id'])
    op.drop_index(op.f('ix_agenda_events_workspace_id'), table_name='agenda_events')
    op.create_index(op.f('ix_agenda_events_team_id'), 'agenda_events', ['team_id'], unique=False)
    op.alter_column('agenda_events', 'external_attendees',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment=None,
               existing_comment='Nombres de asistentes no registrados.',
               existing_nullable=True)
    op.alter_column('agenda_events', 'location',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Ubicación del evento.',
               existing_nullable=True)
    op.alter_column('agenda_events', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descripción detallada del evento.',
               existing_nullable=True)
    op.alter_column('agenda_events', 'summary',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Resumen conciso del evento.',
               existing_nullable=False)
    op.create_table('note_profile_links',
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notas.id'], name=op.f('note_profile_links_note_id_fkey')),
    sa.ForeignKeyConstraint(['profile_id'], ['contact_profiles.id'], name=op.f('note_profile_links_profile_id_fkey')),
    sa.PrimaryKeyConstraint('note_id', 'profile_id', name=op.f('note_profile_links_pkey'))
    )
    op.create_table('chat_message_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_history_pkey'))
    )
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    op.create_table('process_status',
    sa.Column('account_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('account_id', name=op.f('process_status_pkey'))
    )
    # ### end Alembic commands ###
