"""Add etag column to agenda_events

Revision ID: 7e2a574da3cc
Revises: 6f9993f6ad72
Create Date: 2025-11-17 19:38:08.406800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e2a574da3cc'
down_revision: Union[str, Sequence[str], None] = '6f9993f6ad72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_chat_history')
    op.add_column('agenda_events', sa.Column('etag', sa.String(), nullable=True))
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    op.add_column('notas', sa.Column('etag', sa.String(), nullable=True))
    op.drop_constraint(op.f('profiles_account_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('teams_admin_id_fkey'), 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'accounts', ['admin_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_account_personal_topic', 'user_document_topics', ['account_id', 'name'], unique=True, postgresql_where=sa.text('workspace_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_account_personal_topic', table_name='user_document_topics', postgresql_where=sa.text('workspace_id IS NULL'))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_admin_id_fkey'), 'teams', 'accounts', ['admin_id'], ['id'])
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_account_id_fkey'), 'profiles', 'accounts', ['account_id'], ['id'])
    op.drop_column('notas', 'etag')
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.drop_column('agenda_events', 'etag')
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    # ### end Alembic commands ###
