"""Añadir campo status a la tabla Task

Revision ID: b64d41572ae8
Revises: fdc15411c20d
Create Date: 2025-11-18 21:51:27.753322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64d41572ae8'
down_revision: Union[str, Sequence[str], None] = 'fdc15411c20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(length=50), nullable=True, comment='Estado de la tarea para tableros Kanban (ej. Pendiente, En Progreso, Completado).'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    # ### end Alembic commands ###
