"""add mfa fields to account

Revision ID: bb9b21bbc3c9
Revises: 2f8c0071b1af
Create Date: 2026-01-08 01:15:59.238684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9b21bbc3c9'
down_revision: Union[str, Sequence[str], None] = '2f8c0071b1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('langchain_chat_history') # Comentamos esto para evitar errores si la tabla ya no existe o es necesaria
    op.add_column('accounts', sa.Column('mfa_enabled', sa.Boolean(), nullable=True, comment='Indica si el usuario tiene MFA habilitado.'))
    op.execute("UPDATE accounts SET mfa_enabled = FALSE WHERE mfa_enabled IS NULL")
    op.alter_column('accounts', 'mfa_enabled', nullable=False, server_default=sa.false())
    op.add_column('accounts', sa.Column('mfa_secret', sa.String(length=255), nullable=True, comment='Secreto TOTP para MFA.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'mfa_secret')
    op.drop_column('accounts', 'mfa_enabled')
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    # ### end Alembic commands ###
