"""add_start_date_and_end_date_to_tasks

Revision ID: e4464a48c948
Revises: e927a11231a9
Create Date: 2025-11-20 18:54:40.733962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4464a48c948'
down_revision: Union[str, Sequence[str], None] = 'e927a11231a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('langchain_chat_history')
    op.alter_column('accounts', 'custom_system_prompt',
               existing_type=sa.TEXT(),
               comment='Prompt de sistema específico para la IA de esta cuenta.',
               existing_comment='Prompt de sistema personalizado para la IA de esta cuenta.',
               existing_nullable=True)
    op.add_column('agenda_events', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    op.add_column('tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'end_date')
    op.drop_column('tasks', 'start_date')
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.drop_column('agenda_events', 'end_date')
    op.alter_column('accounts', 'custom_system_prompt',
               existing_type=sa.TEXT(),
               comment='Prompt de sistema personalizado para la IA de esta cuenta.',
               existing_comment='Prompt de sistema específico para la IA de esta cuenta.',
               existing_nullable=True)
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    # ### end Alembic commands ###
