"""Add TTS configuration to Account model

Revision ID: eeedefc8932c
Revises: 6b2cd28cd638
Create Date: 2026-02-11 21:41:19.327704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeedefc8932c'
down_revision: Union[str, Sequence[str], None] = '6b2cd28cd638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('tts_provider', sa.String(length=50), nullable=True, comment="Proveedor de TTS preferido (e.g., 'openai', 'elevenlabs')."))
    op.add_column('accounts', sa.Column('tts_model', sa.String(length=255), nullable=True, comment='Modelo de TTS preferido.'))
    op.add_column('accounts', sa.Column('tts_voice', sa.String(length=255), nullable=True, comment='Voz de TTS preferida.'))
    op.add_column('accounts', sa.Column('tts_speed', sa.Float(), nullable=True, comment='Velocidad de la generación de voz (e.g., 1.0).'))
    op.alter_column('accounts', 'use_prompt_tooling',
               existing_type=sa.BOOLEAN(),
               comment='Si es True, fuerza el uso de documentación de herramientas en el prompt en lugar de Function Calling nativo.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.alter_column('accounts', 'use_prompt_tooling',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si es True, fuerza el uso de documentación de herramientas en el prompt en lugar de Function Calling nativo.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('accounts', 'tts_speed')
    op.drop_column('accounts', 'tts_voice')
    op.drop_column('accounts', 'tts_model')
    op.drop_column('accounts', 'tts_provider')
    # ### end Alembic commands ###
