"""Add is_private to agenda_events

Revision ID: f98e11034e20
Revises: 0eca9c52eb37
Create Date: 2025-11-29 15:53:29.478678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f98e11034e20'
down_revision: Union[str, Sequence[str], None] = '0eca9c52eb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Usar SQL bruto con IF EXISTS para evitar errores si las tablas ya fueron eliminadas
    from sqlalchemy import text
    
    conn = op.get_bind()
    
    # Eliminar tabla langchain_chat_history si existe
    conn.execute(text("DROP TABLE IF EXISTS langchain_chat_history CASCADE"))
    
    # Eliminar índices de team_members si existen
    conn.execute(text("DROP INDEX IF EXISTS ix_team_member_account_id"))
    conn.execute(text("DROP INDEX IF EXISTS ix_team_member_team_id"))
    conn.execute(text("DROP INDEX IF EXISTS ix_team_members_account_id"))
    conn.execute(text("DROP INDEX IF EXISTS ix_team_members_team_id"))
    
    # Eliminar tabla team_members si existe
    conn.execute(text("DROP TABLE IF EXISTS team_members CASCADE"))
    
    # Eliminar foreign keys y columnas que dependen de teams
    conn.execute(text("DROP INDEX IF EXISTS idx_user_document_topics_team_id"))
    conn.execute(text("DROP INDEX IF EXISTS ix_account_team_topic"))
    
    # Eliminar FK si existe
    conn.execute(text("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.table_constraints 
                WHERE constraint_name = 'user_document_topics_team_id_fkey'
            ) THEN
                ALTER TABLE user_document_topics DROP CONSTRAINT user_document_topics_team_id_fkey;
            END IF;
        END $$;
    """))
    
    # Eliminar columna team_id si existe en user_document_topics
    conn.execute(text("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'user_document_topics' AND column_name = 'team_id'
            ) THEN
                ALTER TABLE user_document_topics DROP COLUMN team_id;
            END IF;
        END $$;
    """))
    
    # Eliminar tabla teams si existe
    conn.execute(text("DROP TABLE IF EXISTS teams CASCADE"))
    
    # Agregar columna is_private a agenda_events si no existe
    conn.execute(text("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'agenda_events' AND column_name = 'is_private'
            ) THEN
                ALTER TABLE agenda_events ADD COLUMN is_private BOOLEAN NOT NULL DEFAULT FALSE;
                COMMENT ON COLUMN agenda_events.is_private IS 'Indica si el evento es privado (solo visible para el creador).';
            END IF;
        END $$;
    """))
    
    # Eliminar índices y columnas relacionadas con teams de otras tablas
    conn.execute(text("DROP INDEX IF EXISTS ix_analyzed_pairs_document_ids"))
    conn.execute(text("DROP INDEX IF EXISTS idx_langchain_pg_embedding_team_id"))
    
    # Eliminar columnas de langchain_pg_embedding si existen
    conn.execute(text("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'langchain_pg_embedding' AND column_name = 'visibility_teams'
            ) THEN
                ALTER TABLE langchain_pg_embedding DROP COLUMN visibility_teams;
            END IF;
        END $$;
    """))
    
    conn.execute(text("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'langchain_pg_embedding' AND column_name = 'team_id'
            ) THEN
                ALTER TABLE langchain_pg_embedding DROP COLUMN team_id;
            END IF;
        END $$;
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_document_topics', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_document_topics_team_id_fkey'), 'user_document_topics', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_account_team_topic'), 'user_document_topics', ['account_id', 'team_id', 'name'], unique=True, postgresql_where='(team_id IS NOT NULL)')
    op.create_index(op.f('idx_user_document_topics_team_id'), 'user_document_topics', ['team_id'], unique=False)
    op.add_column('langchain_pg_embedding', sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True, comment='UUID of the team this document is shared with'))
    op.add_column('langchain_pg_embedding', sa.Column('visibility_teams', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSONB array of team UUIDs that have visibility to this document'))
    op.create_index(op.f('idx_langchain_pg_embedding_team_id'), 'langchain_pg_embedding', ['team_id'], unique=False)
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.drop_column('agenda_events', 'is_private')
    op.create_table('teams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Nombre del equipo.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID del administrador del equipo.'),
    sa.ForeignKeyConstraint(['admin_id'], ['accounts.id'], name='teams_admin_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='teams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Rol del miembro en el equipo (ej. admin, member).'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('team_members_account_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('team_members_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('team_members_pkey')),
    sa.UniqueConstraint('team_id', 'account_id', name=op.f('_team_account_member_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_account_id'), 'team_members', ['account_id'], unique=False)
    op.create_index(op.f('ix_team_member_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_member_account_id'), 'team_members', ['account_id'], unique=False)
    op.create_table('langchain_chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_chat_history_pkey'))
    )
    # ### end Alembic commands ###
