"""Add tts_api_base to Account

Revision ID: fc0c81ed56cb
Revises: c3708875e512
Create Date: 2026-03-27 02:06:23.021190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc0c81ed56cb'
down_revision: Union[str, Sequence[str], None] = 'c3708875e512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('idx_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('message_intents')
    op.drop_table('craving_triggers')
    op.drop_table('llm_logs')
    op.drop_table('checkin_streaks')
    op.drop_table('coping_strategies')
    op.drop_table('sharing_invitations')
    op.drop_table('message_attachments')
    op.drop_table('scenario_configs')
    op.drop_table('messages')
    op.drop_table('strategy_usage')
    op.drop_table('checkins')
    op.drop_table('mood_history')
    op.drop_table('notifications')
    op.drop_table('cravings')
    op.drop_table('profile_settings')
    op.drop_table('quick_responses')
    op.drop_table('substance_preferences')
    op.drop_table('wall_messages')
    op.drop_table('conversations')
    op.drop_table('conversation_sessions')
    op.drop_table('context_history')
    op.drop_table('users')
    op.drop_table('craving_patterns')
    op.add_column('accounts', sa.Column('tts_api_base', sa.String(length=255), nullable=True, comment='URL base opcional para un servicio de TTS local o custom.'))
    op.alter_column('accounts', 'tts_region',
               existing_type=sa.VARCHAR(length=50),
               comment="Región del servicio de TTS (e.g., 'eastus' para Azure).",
               existing_comment='Región del servicio de TTS (e.g., eastus para Azure).',
               existing_nullable=True)
    op.alter_column('accounts', 'disabled_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Lista de IDs de skills desactivadas por el usuario.',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('agenda_events', 'caldav_uid',
               existing_type=sa.VARCHAR(length=255),
               comment='UID específico para sincronización CalDAV.',
               existing_nullable=True)
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    op.drop_column('langchain_pg_embedding', 'is_graph_processed')
    op.alter_column('notas', 'visual_content',
               existing_type=sa.TEXT(),
               comment='Contenido HTML generado preservando el diseño visual.',
               existing_comment='Contenido HTML generado por OnlyOffice para preservar el diseño visual.',
               existing_nullable=True)
    op.drop_index(op.f('ix_notas_caldav_uid'), table_name='notas')
    op.drop_column('notas', 'caldav_uid')
    op.alter_column('profiles', 'gustos',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'intereses',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'otros_datos',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'system_prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'caldav_uid',
               existing_type=sa.VARCHAR(length=255),
               comment='UID específico para sincronización CalDAV.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'caldav_uid',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UID específico para sincronización CalDAV.',
               existing_nullable=True)
    op.alter_column('profiles', 'system_prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'otros_datos',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'intereses',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'gustos',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('notas', sa.Column('caldav_uid', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_notas_caldav_uid'), 'notas', ['caldav_uid'], unique=False)
    op.alter_column('notas', 'visual_content',
               existing_type=sa.TEXT(),
               comment='Contenido HTML generado por OnlyOffice para preservar el diseño visual.',
               existing_comment='Contenido HTML generado preservando el diseño visual.',
               existing_nullable=True)
    op.add_column('langchain_pg_embedding', sa.Column('is_graph_processed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.alter_column('agenda_events', 'caldav_uid',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UID específico para sincronización CalDAV.',
               existing_nullable=True)
    op.alter_column('accounts', 'disabled_skills',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Lista de IDs de skills desactivadas por el usuario.',
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('accounts', 'tts_region',
               existing_type=sa.VARCHAR(length=50),
               comment='Región del servicio de TTS (e.g., eastus para Azure).',
               existing_comment="Región del servicio de TTS (e.g., 'eastus' para Azure).",
               existing_nullable=True)
    op.drop_column('accounts', 'tts_api_base')
    op.create_table('craving_patterns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('substance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('pattern_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('frequency_per_week', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_intensity', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('common_triggers', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('effective_strategies', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'identified'::character varying"), autoincrement=False, nullable=True),
    sa.Column('first_observed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_observed', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('occurrence_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('craving_patterns_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('craving_patterns_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'patient'::character varying"), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('onboarding_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('profile_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('two_factor_secret', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('llm_provider', sa.VARCHAR(length=50), server_default=sa.text("'openai'::character varying"), autoincrement=False, nullable=True),
    sa.Column('llm_model', sa.VARCHAR(length=50), server_default=sa.text("'gpt-4'::character varying"), autoincrement=False, nullable=True),
    sa.Column('llm_api_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('context_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('context_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('importance', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.Column('times_referenced', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('last_referenced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], name=op.f('context_history_source_message_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('context_history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('context_history_pkey')),
    sa.UniqueConstraint('user_id', 'context_type', 'key', name=op.f('context_history_user_id_context_type_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('context_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_mood_before', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_mood_after', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('emotional_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('topics_discussed', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('strategies_shared', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('resources_recommended', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages_in_session', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('session_outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_sessions_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversation_sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_sessions_pkey'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), server_default=sa.text("'Nueva conversación'::character varying"), autoincrement=False, nullable=True),
    sa.Column('scenario_type', sa.VARCHAR(length=50), server_default=sa.text("'apoyo_emocional'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_satisfaction', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('helpfulness_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relevance_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contains_crisk', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('escalated_to_emergency', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('required_human_intervention', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('scenario_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_table('wall_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['users.id'], name=op.f('wall_messages_family_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('wall_messages_patient_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('wall_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('wall_messages_pkey'))
    )
    op.create_table('substance_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('substance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('substance_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('current_status', sa.VARCHAR(length=30), server_default=sa.text("'activo'::character varying"), autoincrement=False, nullable=True),
    sa.Column('use_frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_use_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('target_cease_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('substance_preferences_pkey'))
    )
    op.create_table('quick_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('trigger_phrase', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('applicable_scenarios', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'es'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quick_responses_pkey'))
    )
    op.create_table('profile_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('checkin_frequency', sa.VARCHAR(length=20), server_default=sa.text("'diaria'::character varying"), autoincrement=False, nullable=True),
    sa.Column('checkin_reminder_time', postgresql.TIME(), server_default=sa.text("'09:00:00'::time without time zone"), autoincrement=False, nullable=True),
    sa.Column('checkin_reminder_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('data_sharing_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('share_with_family', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('share_progress_weekly', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('anonymous_analytics', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('auto_detect_crisis', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('emergency_contacts_notified', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('location_sharing_emergency', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('chatbot_personality', sa.VARCHAR(length=50), server_default=sa.text("'apoyo'::character varying"), autoincrement=False, nullable=True),
    sa.Column('response_detail_level', sa.VARCHAR(length=20), server_default=sa.text("'balanceado'::character varying"), autoincrement=False, nullable=True),
    sa.Column('memory_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_settings_pkey')),
    sa.UniqueConstraint('profile_id', name=op.f('profile_settings_profile_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cravings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('substance_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('substance_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('intensity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('coping_strategies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('outcome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('consumed_quantity', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('consumed_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('consequences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('craving_start_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('craving_end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('intensity >= 1 AND intensity <= 10', name=op.f('cravings_intensity_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cravings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cravings_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('mood_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mood_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('mood_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anxiety_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emotional_tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('weekly_average_mood', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('weekly_average_anxiety', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('weekly_average_energy', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('mood_trend', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mood_history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mood_history_pkey')),
    sa.UniqueConstraint('user_id', 'mood_date', name=op.f('unique_user_mood_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('checkin_type', sa.VARCHAR(length=30), server_default=sa.text("'diario'::character varying"), autoincrement=False, nullable=False),
    sa.Column('mood_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anxiety_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emotional_tags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('consumed_substances', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('risk_situation', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('risk_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('coping_strategy_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sleep_hours', sa.NUMERIC(precision=4, scale=1), autoincrement=False, nullable=True),
    sa.Column('sleep_quality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercised_today', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('exercise_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exercise_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('social_interaction', sa.VARCHAR(length=50), server_default=sa.text("'ninguna'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('checkin_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('checkin_time', postgresql.TIME(), server_default=sa.text('CURRENT_TIME'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('anxiety_score >= 1 AND anxiety_score <= 10', name=op.f('checkins_anxiety_score_check')),
    sa.CheckConstraint('energy_score >= 1 AND energy_score <= 10', name=op.f('checkins_energy_score_check')),
    sa.CheckConstraint('mood_score >= 1 AND mood_score <= 10', name=op.f('checkins_mood_score_check')),
    sa.CheckConstraint('sleep_quality >= 1 AND sleep_quality <= 10', name=op.f('checkins_sleep_quality_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('checkins_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('checkins_pkey')),
    sa.UniqueConstraint('user_id', 'checkin_date', name=op.f('unique_user_checkin_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('strategy_usage',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('craving_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('was_effective', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['craving_id'], ['cravings.id'], name=op.f('strategy_usage_craving_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['coping_strategies.id'], name=op.f('strategy_usage_strategy_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('strategy_usage_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('strategy_usage_pkey'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active_scenario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content_filter_passed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('inappropriate_content_flags', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('resources_included', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['user'::character varying, 'assistant'::character varying, 'system'::character varying]::text[])", name=op.f('messages_role_check')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('messages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_table('scenario_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('scenario_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('scenario_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('0.7'), autoincrement=False, nullable=True),
    sa.Column('max_tokens', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=True),
    sa.Column('enabled_skills', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('trigger_conditions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=20), server_default=sa.text("'1.0.0'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('scenario_configs_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('scenario_configs_pkey')),
    sa.UniqueConstraint('scenario_type', name=op.f('scenario_configs_scenario_type_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('message_attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attachment_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_attachments_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_attachments_pkey'))
    )
    op.create_table('sharing_invitations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('invitation_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'rejected'::character varying, 'revoked'::character varying]::text[])", name=op.f('sharing_invitations_status_check')),
    sa.ForeignKeyConstraint(['family_id'], ['users.id'], name=op.f('sharing_invitations_family_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('sharing_invitations_patient_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sharing_invitations_pkey')),
    sa.UniqueConstraint('invitation_code', name=op.f('sharing_invitations_invitation_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('patient_id', 'family_id', name=op.f('sharing_invitations_patient_id_family_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('coping_strategies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('effectiveness_rating', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('times_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('times_successful', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('success_rate', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('when_to_use', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('coping_strategies_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('coping_strategies_pkey'))
    )
    op.create_table('checkin_streaks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('streak_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('current_streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('longest_streak', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total_completions', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_completion_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('streak_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('longest_streak_start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('longest_streak_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('checkin_streaks_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('checkin_streaks_pkey')),
    sa.UniqueConstraint('user_id', 'streak_type', name=op.f('unique_user_streak_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('llm_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('finish_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_usd', sa.NUMERIC(precision=12, scale=8), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('llm_logs_conversation_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('llm_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_logs_pkey'))
    )
    op.create_table('craving_triggers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('trigger_description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('frequency', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('avg_intensity_when_triggered', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('consumption_probability', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('context_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('craving_triggers_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('craving_triggers_pkey'))
    )
    op.create_table('message_intents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('emotion_detected', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('emotion_confidence', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('suggested_scenario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_crisis_indicator', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_relapse_risk', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_intents_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_intents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_intents_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('issued_from', sa.VARCHAR(length=20), server_default=sa.text("'api'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('refresh_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('refresh_tokens_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contact_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_notified_on_crisis', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.id'], name=op.f('emergency_contacts_contact_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('emergency_contacts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('emergency_contacts_pkey'))
    )
    # ### end Alembic commands ###
