"""Add duration_minutes column to agenda_events

Revision ID: fdc15411c20d
Revises: 98f9f97824c1
Create Date: 2025-11-17 20:01:22.682356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc15411c20d'
down_revision: Union[str, Sequence[str], None] = '98f9f97824c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_events', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_analyzed_pairs_document_ids'), table_name='analyzed_pairs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_analyzed_pairs_document_ids'), 'analyzed_pairs', ['document_id_a', 'document_id_b'], unique=False)
    op.drop_column('agenda_events', 'duration_minutes')
    # ### end Alembic commands ###
